### PR TITLE
fix parent paths, dot filenames

### PR DESCRIPTION
**Pull request by jspaine**
Had problems with patterns like in the added test cases, seems to fix them.

### CODE REVIEW

**Comment by jurassix** [comment]
Thx! I'll review this and comment with any suggestions I find.

**Comment by jurassix** [comment]
Looks great. Nice work! merging in now. I will release this and publish a new version of [atom-javascript-refactor](https://github.com/jurassix/atom-javascript-refactor)

**Comment by jurassix** [comment]
Note, I'm also adding more cases to the relative and specifier test fixtures to ensure we have full coverage for this usage.

**Comment by jspaine** [comment]
Thanks, same to you! Just saved me a lot of tedious work :smile:

There was one case it still didn't pick up on - `require('path/to/foo')()`. I don't know enough about jscodeshift to know how to fix that.

**Comment by jurassix** [comment]
@jspaine is you can open an issue to capture this use case I'll track it down.

**Pull request merged**
